"""Data models for the final engineering report."""
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

from app.models.analysis import DimensionScore


class EngineeringReport(BaseModel):
    """The final synthesized report generated by the ReportAgent."""
    repo_target: str
    analyzed_at: datetime
    data_source: Literal["github", "filesystem"]
    overall_score: float = Field(ge=0.0, le=10.0)
    dimensions: list[DimensionScore]
    executive_summary: str
    recommendations: list[str]
    markdown_report: str
